config/routes.rb
DerbyPractice::Application.routes.draw do
  resources :events
  
  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :capacity, :date, :description, :location, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end
	
	  def new
    @event = Event.new
  end
 
  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to events_url
    else
      render action: "new"
    end
  end
   
  def edit
    @event = Event.find(params[:id])
  end
 
  def update
    @event = Event.find(params[:id])
 
    if @event.update_attributes(params[:event])
      redirect_to events_path
    else
      render action: "edit"
    end
  end
  
   def show
    @event = Event.find(params[:id])
  end
  
   def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h2>Edit <%= @event.name %></h2>
 
<div class="well">
<%= form_for @event do |form| %>
  <div>
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>
 
  <div>
    <%= form.label :description %><br />
    <%= form.text_field :description %>
  </div>
 
  <div>
    <%= form.label :location %><br />
    <%= form.text_field :location %>
  </div>
 
  <div>
    <%= form.label :date %><br />
    <%= form.text_field :date %>
  </div>
   <div>
    <%= form.label :capacity %><br />
    <%= form.text_field :capacity %>
  </div>
</div>
  <p><%= form.submit %></p>
<% end %>

app/views/events/index.html.erb
<div class="hero-unit">
  <h1>Derby Practice</h1>
  <p>Need to plan a practice? This is the motherfucking place to do it.</p>
  <p><%= link_to "Plan a Practice", new_event_url, :class => "brn btn-primary btn-large" %></p>
</div>
 
<table class="table table-striped">
  <thead> 
    <th>Event</th>
    <th>Date & Time</th>
    <th>Actions</td>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td>
          <%= link_to event.name, event_path(event) %> - <%= event.description %><br />
          Where? <%= event.location %> | Capacity <%= event.capacity %>
        </td>
        <td>
			<%= link_to event.date, event_path(event) %> 
        </td>
        <td>
          <%= link_to "Edit", edit_event_path(event) %>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody> 
</table>

app/views/events/new.html.erb
<h2>Create a New Practice</h2>
<%= form_for @event do |form| %>
<div class="well">
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
 
  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  
    <div>
<%= form.label :date %>
  <div id="datetimepicker2" class="input-append">
    <input data-format="yyyy, MM, dd, HH, mm, ss" type="text"></input>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>
<script type="text/javascript">
  $(function() {
    $('#datetimepicker2').datetimepicker({
      language: 'en',
      pick12HourFormat: true
    });
  });
</script>
  </div>
  
   <div>
    <%= form.label :capacity %><br />
    <%= form.text_field :capacity %>
  </div>
 </div>
  <p><%= form.submit %></p>
<% end %>

app/views/events/show.html.erb
<div class="well">
<h1><%= @event.name %></h1>
<h3>What:</h3>
<h4><%= @event.description %></h4>
<h3>Where:</h3>
<p><%= @event.location %></p>
<h3>When:</h3>
<p><%= @event.date %></p>
<h3>How many people:</h3>
<p><%= @event.capacity %></p>
</div>
<%= link_to "Edit", edit_event_path(), :class => "brn btn-primary btn-large" %>
<%= link_to 'Destroy', (), method: :delete, :class => "brn btn-primary btn-large", data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DerbyPractice</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
  <div class="container">
    <%= yield %>
  </div>
  
</body>
</html>